post http://localhost:8000/create-temp-and-humid
Content-Type: application/json

{
    "temp": 12,
    "humid": 13
}

###
get http://localhost:8000/list-temp-and-humid


###
post http://localhost:8000/set-fans
Content-Type: application/json

{"fans": [0,0,1]}

###
get http://localhost:8000/get-fans